
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      # Install dotnet wasm buildtools workload
      - name: Install .NET WASM Build Tools
        run: dotnet workload install wasm-tools
          
      # Publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish SigmaExplorer/Client/SigmaExplorer.Client.csproj -c:Release -p:GHPages=true -o dist/Web --nologo

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/Web/wwwroot
          
      - name: Commit wwwroot to GitHub Pages testnet
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          token: ${{ secrets.TESTNETPAT }}
          repository-name: pulsarz\sigmaexplorer-testnet
          BRANCH: master
          FOLDER: dist/Web/wwwroot
